name: pytest

on: 
  push: 
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      
      - name: Testing with pytest
        run: |
          pytest -v 
